export const SEARCH_NOVIE_START = "SEARCH_NOVIE_START";
export const SEARCH_NOVIE_ERROR = "SEARCH_NOVIE_ERROR";
export const SEARCH_NOVIE_COMPLETE = "SEARCH_NOVIE_COMPLETE";


export const SEARCH_NOVIE_BY_ID_START = "SEARCH_NOVIE_BY_ID_START";
export const SEARCH_NOVIE_BY_ID_ERROR = "SEARCH_NOVIE_BY_ID_ERROR";
export const SEARCH_NOVIE_BY_ID_COMPLETE = "SEARCH_NOVIE_BY_ID_COMPLETE";